### ISSUE TITLE
Failed to build libaccessom2 in ACCESS-OM2 with openmpi@5.0.8

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/libaccessom2#25]
I was unable to build libaccessom2 as part of ACCESS-OM2 using openmpi@5.0.8. Build logs are [here](https://github.com/ACCESS-NRI/ACCESS-OM2/actions/runs/17903251491/job/50899841801) and the relevant section is copied below for longevity:

```
==> [2025-09-22-13:38:15.408447] libaccessom2: Executing phase: 'cmake'
==> [2025-09-22-13:38:26.372748] libaccessom2: Executing phase: 'build'
==> [2025-09-22-13:38:28.254749] Error: ProcessError: Command exited with status 2:
    'make' '-j16'

6 errors found in build log:
     53    /apps/cmake/3.24.2/bin/cmake -E cmake_copy_f90_mod include/error_han
           dler.mod CMakeFiles/util.dir/error_handler.mod.stamp Intel
     54    /apps/cmake/3.24.2/bin/cmake -E touch CMakeFiles/util.dir/libutil/sr
           c/error_handler.F90.o.provides.build
     55    [  9%] Building Fortran object CMakeFiles/util.dir/libutil/src/logge
           r.F90.o
     56    [  9%] Building Fortran object CMakeFiles/util.dir/libutil/src/util.
           F90.o
     57    /apps/openmpi/5.0.8/bin/mpif90 -DCMAKE_YATM_VERSION="'2.0.202212'"  
           -r8 -fpe0 -fp-model precise -fp-model source -align all -traceback -
           g3 -O2 -axCORE-AVX2 -debug all -check none  -module include -c /scra
           tch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2025.0
           5.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/libutil/
           src/logger.F90 -o CMakeFiles/util.dir/libutil/src/logger.F90.o
     58    /apps/openmpi/5.0.8/bin/mpif90 -DCMAKE_YATM_VERSION="'2.0.202212'"  
           -r8 -fpe0 -fp-model precise -fp-model source -align all -traceback -
           g3 -O2 -axCORE-AVX2 -debug all -check none  -module include -c /scra
           tch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2025.0
           5.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/libutil/
           src/util.F90 -o CMakeFiles/util.dir/libutil/src/util.F90.o
  >> 59    /scratch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2
           025.05.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/lib
           util/src/logger.F90(3): error #7012: The module file cannot be read.
             Its format requires a more recent F90 compiler.   [MPI]
     60    use mpi
     61    ----^
  >> 62    /scratch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2
           025.05.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/lib
           util/src/logger.F90(4): error #6580: Name in only-list does not exis
           t or is not accessible.   [ASSERT]
     63    use error_handler, only : assert
     64    --------------------------^
  >> 65    /scratch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2
           025.05.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/lib
           util/src/logger.F90(57): error #6404: This name does not have a type
           , and must have an explicit type.   [MPI_COMM_WORLD]
     66            call MPI_Comm_rank(MPI_COMM_WORLD, pe, err)
     67    ---------------------------^
     68    compilation aborted for /scratch/tm70/***/tmp/spack-stage/spack-
           stage-libaccessom2-git.2025.05.001_access-om2-etrebc2ex552mzv4stksvu
           aiaye6skqe/spack-src/libutil/src/logger.F90 (code 1)
  >> 69    make[2]: *** [CMakeFiles/util.dir/build.make:91: CMakeFiles/util.dir
           /libutil/src/logger.F90.o] Error 1
     70    make[2]: *** Waiting for unfinished jobs....
     71    /scratch/tm70/***/tmp/spack-stage/spack-stage-libaccessom2-git.2
           025.05.001_access-om2-etrebc2ex552mzv4stksvuaiaye6skqe/spack-src/lib
           util/src/util.F90(43): remark #15009: util_mod_mp_read_data_ has bee
           n targeted for automatic cpu dispatch
     72    make[2]: Leaving directory '/scratch/tm70/***/tmp/spack-stage/sp
           ack-stage-libaccessom2-git.2025.05.001_access-om2-etrebc2ex552mzv4st
           ksvuaiaye6skqe/spack-build-etrebc2'
  >> 73    make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/util.dir/all] Erro
           r 2
     74    make[1]: Leaving directory '/scratch/tm70/***/tmp/spack-stage/sp
           ack-stage-libaccessom2-git.2025.05.001_access-om2-etrebc2ex552mzv4st
           ksvuaiaye6skqe/spack-build-etrebc2'
  >> 75    make: *** [Makefile:139: all] Error 2
```

Linking appears to have failed. I was able to build fine with openmpi@4 (tested both 4.0.2 and 4.1.7 in the above linked PR).

I don't have time to investigate more deeply at the moment.
